ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "nbdev_hello_world"
  site-url: "https://lpattori.github.io/nbdev_hello_world/"
  description: "Hello world test with nbdev"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: main
  repo-url: "https://github.com/lpattori/nbdev-hello-world/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/lpattori/nbdev-hello-world/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
